[template]
src = "traefik.tmpl.toml"
dest = "traefik.toml"
prefix = "traefik"
keys = [
  "/debug",
  "/default/entrypoints",
  "/insecure/skip",
  "/log/level",
  "/http/address",
  "/http/compression",
  "/http/port",
  "/https/address",
  "/https/enable",
  "/https/compression",
  "/https/port",
  "/marathon/dcos/token",
  "/marathon/dialer/timeout",
  "/marathon/domain",
  "/marathon/enable",
  "/marathon/endpoint",
  "/marathon/expose",
  "/marathon/force/task/hostname",
  "/marathon/groups/as/subdomains",
  "/marathon/keep/alive",
  "/marathon/lb/compatibility",
  "/marathon/respect/readiness/checks",
  "/marathon/watch",
]
