[template]
src = "traefik.tmpl.toml"
dest = "traefik.toml"
prefix = "traefik"
keys = [
  "/acme/email",
  "/acme/enable",
  "/acme/entrypoint",
  "/acme/onhostrule",
  "/acme/storage",
  "/api/address",
  "/api/compression",
  "/api/dashboard",
  "/api/debug",
  "/api/enable",
  "/api/port",
  "/debug",
  "/default/entrypoints",
  "/insecure/skip",
  "/log/level",
  "/file/name",
  "/file/watch",
  "/http/address",
  "/http/compression",
  "/http/port",
  "/https/address",
  "/https/enable",
  "/https/compression",
  "/https/port",
  "/marathon/dcos/token",
  "/marathon/dialer/timeout",
  "/marathon/domain",
  "/marathon/enable",
  "/marathon/endpoint",
  "/marathon/expose",
  "/marathon/force/task/hostname",
  "/marathon/groups/as/subdomains",
  "/marathon/keep/alive",
  "/marathon/lb/compatibility",
  "/marathon/respect/readiness/checks",
  "/marathon/watch",
  "/mesos/domain",
  "/mesos/enable",
  "/mesos/endpoint",
  "/mesos/expose",
  "/mesos/filename",
  "/mesos/groups/as/subdomains",
  "/mesos/ip/sources",
  "/mesos/refresh",
  "/mesos/watch",
  "/mesos/zk/timeout",
  "/ping/address",
  "/ping/enable",
  "/ping/port",
  "/prometheus/buckets",
  "/prometheus/entrypoint",
  "/rancher/domain",
  "/rancher/enable",
  "/rancher/expose",
  "/rancher/filename",
  "/rancher/healthcheck",
  "/rancher/intervalpoll",
  "/rancher/refresh",
  "/rancher/watch",
]
